### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by ChristophHoyer** [ZenHubHQ/zenhub-enterprise#10]
Hej there!
The link to "virtual machine" in README.md, chapter 1.4 is not working.

**Comment by EvHaus** [comment]
Thanks for the note @ChristophHoyer. We'll get that fixed. We haven't yet shipped the VM-based docs for 3.0 but it's coming very soon.

**Comment by toorog** [comment]
@EvHaus So how are we supposed to setup a VM as per today? Are there any alternative doc sources available?

**Comment by dylanmartyn** [comment]
Hey @ChristophHoyer and @toorog. If you don't want to wait for 3.0, you can get started by deploying 2.44, then migrate when we release 3.0. To get started with 2.44 the best thing to do would be to contact us through our website (https://www.zenhub.com/enterprise) and we'll send over the required materials.

**Comment by EvHaus** [comment]
This has been fixed. The documentation for VM configuration is available at https://github.com/ZenHubHQ/zenhub-enterprise/tree/master/virtual-machine VM support is available in ZHE 3.1 beta.
