### ISSUE TITLE
New version means my boards are only in a small section of the screen

### ISSUE THREAD

**Issue by JamesBlandford** [ZenHubHQ/zenhub-enterprise#17]
Hi ZenHub,
I have recently had an update to my ZenHub Enterprise system and now I can only see a few boards, whereas before it was MUCH wider (see below)

Is there a way to hide the sidebar/nav bar and get rid of the whitespace to the right hand side? This wasnt an issue before, its only appeared with this new update.

Here is what it looks like now, I have a widescreen laptop and its restricting my ability to view issues by a large %age:

![image](https://user-images.githubusercontent.com/9812458/118252299-825f9000-b4a0-11eb-9ef6-ea62fc937434.png)

**Comment by JamesBlandford** [comment]
Oh I just found the purple "double arrow" button to hide most of the sidebar, but it still has some extra whitespace either side of the boards, no idea why

**Comment by EvHaus** [comment]
@JamesBlandford Thanks for flagging this. Seems like an issue with the product feature. Could you please submit this as a request to support@zenhub.com

We use this repository for tracking issues specific to the installation and configuration of ZenHub Enterprise On Premise instances.
